version: 2.1
jobs:
  build:
    docker:
      - auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_TOKEN
        image: cimg/android:2023.04
        environment:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
          JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Copy configuration files
          command: cp .circleci/config/* .

      - restore_cache:
          key: v2-dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Run tests
          command: ./gradlew :clean :sdk:test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

workflows:
  workflow:
    jobs:
      - build:
          context:
            - org-global
