apply plugin: 'com.android.library'
apply plugin: 'de.mobilej.unmock'
apply plugin: 'maven-publish'

group='com.github.talkable'

android {
    namespace 'com.talkable.sdk'
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 33
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        // Required for sdk version retrieval to work as of Android Studio 4.1.0: https://issuetracker.google.com/issues/158695880
        buildConfigField 'int', 'VERSION_CODE', "${project.sdk_version_code}"
        buildConfigField 'String', 'VERSION_NAME', "\"${project.sdk_version_name}\""
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    testOptions {
        unitTests {
            returnDefaultValues = true
            all {
                jvmArgs = [
                    '-noverify',
                    '-XX:+IgnoreUnrecognizedVMOptions',
                    '--add-opens=java.base/java.lang=ALL-UNNAMED',
                    '--add-opens=java.base/java.io=ALL-UNNAMED',
                    '--add-opens=java.base/java.util=ALL-UNNAMED',
                    '--add-opens=java.base/java.util.concurrent=ALL-UNNAMED',
                    '--add-opens=java.desktop/java.awt=ALL-UNNAMED',
                    '--add-exports=java.base/sun.nio.ch=ALL-UNNAMED',
                    '--add-opens=java.base/java.net=ALL-UNNAMED',
                    '--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED'
                ]
                systemProperty 'javax.net.ssl.trustStore', 'NONE'
            }
        }
    }
    lint {
        abortOnError false
    }
    buildToolsVersion '36.0.0'

}

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    testImplementation 'junit:junit:4.13.2'

    testImplementation 'org.mockito:mockito-core:4.11.0'
    testImplementation 'org.mockito:mockito-inline:4.11.0'

    androidTestImplementation 'androidx.annotation:annotation:1.8.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:rules:1.6.1'

    implementation 'androidx.annotation:annotation:1.8.2'
    implementation 'com.squareup.okhttp3:okhttp:3.2.0' // update to a new version when https://github.com/square/okhttp/issues/3928 will be fixed
    implementation 'com.squareup.okhttp3:logging-interceptor:3.2.0'
    implementation 'com.facebook.android:facebook-android-sdk:15.2.0'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
}
